# Generated by Django 2.1.3 on 2018-11-18 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_date',
            new_name='contact_date',
        ),
    ]
