# Generated by Django 2.1.3 on 2018-11-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181117_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_data',
            new_name='list_date',
        ),
    ]
